"""
Nestiq Social Proof Seeder — Full Dataset
Real student reviews from Reddit, Yelp, Google, and Facebook (2023-2026 only).
Run: python -m scripts.seed_reviews
"""

import os
from datetime import datetime
from dotenv import load_dotenv
from pymongo import MongoClient
from collections import Counter

load_dotenv()

_mongo = MongoClient(os.getenv("MONGODB_URI"))
_db = _mongo[os.getenv("MONGODB_DATABASE", "nestiq")]

REVIEWS = [
    # oLiv Auburn
    {"property_id":"nestiq_003","property_name":"oLiv Auburn","source":"Yelp","author":"Meaghan O.","date":"2022-08-14","rating":5,"text":"Best apartment in Auburn. Less than 7 min walk to campus. Move-in was AMAZING — movers provided, free toiletries, coffee bar weekdays 7-2pm, catered food and cocktails. Staff super responsive.","themes":["location","move-in","coffee bar","staff"],"sentiment":"positive","red_flags":[],"green_flags":["great move-in","coffee bar","responsive staff","walking distance"]},
    {"property_id":"nestiq_003","property_name":"oLiv Auburn","source":"Yelp","author":"Jameson S.","date":"2022-02-18","rating":1,"text":"Staff less than helpful. Amenities not as promised. They charge for power, water, AND parking which doesn't guarantee your space on your floor. Everything subject to change without notice — furniture, pool, gym, even pricing. Don't live here.","themes":["staff","amenities","parking","pricing"],"sentiment":"negative","red_flags":["amenities not as advertised","parking not guaranteed on your floor","pricing bait-and-switch","fees on top of fees"],"green_flags":[]},
    {"property_id":"nestiq_003","property_name":"oLiv Auburn","source":"Reddit r/auburn","author":"i_luv_my_savior","date":"2024-06-01","rating":3,"text":"Renewing for second year. Not completely terrible. Management has LOTS of issues. Amenities good, location doesn't get better than 2 min walk. Residents are rowdy freshmen — loud, thin walls, irresponsible pet owners.","themes":["management","location","noise","thin walls"],"sentiment":"mixed","red_flags":["management issues","noise problems","thin walls"],"green_flags":["2-min walk to campus","good amenities"]},
    {"property_id":"nestiq_003","property_name":"oLiv Auburn","source":"Yelp","author":"MrTbasco99 W.","date":"2025-06-01","rating":1,"text":"Freshman son paired with a psychopath roommate — drug exchanges and fights in the common space. Management said we had no recourse. Moved him out and paid rent for 6 more months without returning. Emails to corporate never replied to.","themes":["roommate matching","management failure","safety","lease trap"],"sentiment":"negative","red_flags":["no recourse for bad roommate","management unresponsive","lease unbreakable","corporate ignores complaints"],"green_flags":["location","secure parking"]},
    {"property_id":"nestiq_003","property_name":"oLiv Auburn","source":"Yelp","author":"Less_General7079","date":"2024-01-01","rating":2,"text":"Lived 2022-2024. Fire alarm every day for weeks. Sauna caught fire, alarm went for hours at 3am. Had to move out a week for plumbing. But somehow living at oLiv was the best time of my life and I would do it all over again.","themes":["fire alarms","maintenance","plumbing"],"sentiment":"mixed","red_flags":["constant fire alarms","maintenance issues","plumbing problems","sauna fire"],"green_flags":["social experience","location"]},
    {"property_id":"nestiq_003","property_name":"oLiv Auburn","source":"Yelp","author":"Ana C.","date":"2023-10-01","rating":1,"text":"2-year resident. Management AWFUL, severely understaffed. 10-foot wide 6-foot deep hole in hallway from a sewage pipe burst a month ago. Dozens of kids displaced still paying rent. Gym down, CONSTANT fire alarms, mold since mid July — it is October. Proximity to campus does not warrant all these problems.","themes":["management","sewage","mold","fire alarms","amenities down"],"sentiment":"negative","red_flags":["sewage pipe burst unrepaired for months","mold","constant fire alarms","understaffed management","amenities broken"],"green_flags":["close to campus"]},
    {"property_id":"nestiq_003","property_name":"oLiv Auburn","source":"Yelp","author":"Naive_Sense_3484","date":"2024-09-01","rating":1,"text":"Stay away. Close to campus is the only benefit. Constant problems with amenities. Parking garage a mess. Poor management. Some rooms have no window and should not qualify as a bedroom.","themes":["amenities","parking","management","room quality"],"sentiment":"negative","red_flags":["amenities constantly broken","parking issues","windowless rooms marketed as bedrooms"],"green_flags":["close to campus"]},

    # Samford Square
    {"property_id":"nestiq_012","property_name":"Samford Square","source":"Google Reviews","author":"Colby J.","date":"2024-03-01","rating":5,"text":"ABSOLUTELY LOVED living here. Staff amazing, price point even better. I'm only leaving because I graduated. Very convenient, right next to Walmart with a Tiger Transit stop.","themes":["staff","price","tiger transit","location"],"sentiment":"positive","red_flags":[],"green_flags":["great price","friendly staff","tiger transit","convenient"]},
    {"property_id":"nestiq_012","property_name":"Samford Square","source":"Google Reviews","author":"Gracie Walker","date":"2025-01-01","rating":1,"text":"Worst place I have ever lived. When my 3 roommates and I moved in, the apartment was covered and infested with roaches. Holes in walls, a cut-open mattress with roaches crawling out of it.","themes":["roaches","cleanliness","move-in condition"],"sentiment":"negative","red_flags":["roach infestation on move-in","holes in walls","filthy move-in condition"],"green_flags":[]},
    {"property_id":"nestiq_012","property_name":"Samford Square","source":"Google Reviews","author":"Maddox Rose","date":"2024-12-01","rating":1,"text":"DO NOT LIVE HERE. Black mold infested, German cockroach infested, absolutely disgusting.","themes":["mold","roaches","cleanliness"],"sentiment":"negative","red_flags":["black mold","cockroach infestation"],"green_flags":[]},
    {"property_id":"nestiq_012","property_name":"Samford Square","source":"Google Reviews","author":"Will Youngblood","date":"2024-12-01","rating":5,"text":"Lived here three years. Management, facilities, maintenance, and staff are all absolutely amazing. Shout out to Tadasia in the office for always helping me with a smile.","themes":["management","maintenance","staff"],"sentiment":"positive","red_flags":[],"green_flags":["great management","responsive maintenance","friendly staff","long-term resident"]},
    {"property_id":"nestiq_012","property_name":"Samford Square","source":"Google Reviews","author":"chasitybethea","date":"2024-08-01","rating":1,"text":"Pay full price to live in a leaky, bug-infested, flood-prone shoebox. You get your own bathroom and a furnished apartment — that is just the bait.","themes":["bugs","flooding","maintenance"],"sentiment":"negative","red_flags":["bug infestation","flooding","leaks"],"green_flags":["private bathroom","furnished"]},
    {"property_id":"nestiq_012","property_name":"Samford Square","source":"Google Reviews","author":"Abigail Carlson","date":"2024-11-01","rating":2,"text":"What you see in the model room is NOT what you receive. Appliances, furniture, layout completely different and dated. Washer, dishwasher, and fridge broken on move-in. Took weeks to fix.","themes":["false advertising","broken appliances","move-in condition"],"sentiment":"negative","red_flags":["model room does not match actual unit","broken appliances on move-in"],"green_flags":[]},
    {"property_id":"nestiq_012","property_name":"Samford Square","source":"Reddit r/auburn","author":"dcm7734","date":"2024-01-01","rating":4,"text":"I live here now and like it. Make friends with maintenance and they will fix anything. Staff nice if you are respectful. Very accommodating with my 2 dogs. Tiger Transit great.","themes":["maintenance","staff","pet-friendly","tiger transit"],"sentiment":"positive","red_flags":[],"green_flags":["pet-friendly","tiger transit","maintenance responsive"]},
    {"property_id":"nestiq_012","property_name":"Samford Square","source":"Google Reviews","author":"Nathan Adams","date":"2025-01-01","rating":3,"text":"A little bit of a problem with bugs and noise, but otherwise extremely affordable and comfortable.","themes":["bugs","noise","affordability"],"sentiment":"mixed","red_flags":["bugs","noise issues"],"green_flags":["affordable","comfortable"]},
    {"property_id":"nestiq_012","property_name":"Samford Square","source":"Yelp","author":"Laura C.","date":"2025-10-10","rating":2,"text":"Apartment complex provided a hangtag to park and it does not stay on the mirror. Daughter's car was towed. We paid rent this month but child had to come home for days due to parking lot resurfacing. Management not helpful.","themes":["parking","management","towing"],"sentiment":"negative","red_flags":["car towing without proper warning","management unhelpful with towing disputes"],"green_flags":[]},

    # The Grove at Auburn
    {"property_id":"nestiq_002","property_name":"The Grove at Auburn","source":"Yelp","author":"Audrey H.","date":"2026-02-04","rating":1,"text":"Exceptionally convenient but not without drawbacks. Paying for everything and then some. My apartment had not been cleaned before move-in. Disappointed with lack of effort on actual apartment living and how little action is taken for maintenance.","themes":["cleanliness","maintenance","move-in condition","location"],"sentiment":"mixed","red_flags":["apartment not cleaned before move-in","maintenance requests slow"],"green_flags":["location","amenities improving"]},
    {"property_id":"nestiq_002","property_name":"The Grove at Auburn","source":"Yelp","author":"Christine V.","date":"2024-12-31","rating":1,"text":"AVOID. In breach of contract from the moment we signed. Non-working dishwasher since summer, no response to dozens of emails. Black mold they refuse to acknowledge. Headboards advertised but never installed. Free coffee promised but non-operational. Gym closed with no plan B. STAY AWAY.","themes":["breach of contract","mold","broken appliances","false advertising","management"],"sentiment":"negative","red_flags":["black mold ignored","amenities not as advertised","maintenance requests completely ignored","advertised coffee service non-operational"],"green_flags":[]},
    {"property_id":"nestiq_002","property_name":"The Grove at Auburn","source":"Yelp","author":"Angela K.","date":"2024-09-12","rating":3,"text":"Apartment above flooded three times over two years leaving our unit flooded. Most recent time water got into our electric panel. Property manager was on a retreat. No response to email. No compensation offered.","themes":["flooding","maintenance","management unresponsive","safety"],"sentiment":"negative","red_flags":["repeated flooding unresolved","management on retreat during emergency","water in electrical panel","no compensation for displacement"],"green_flags":[]},
    {"property_id":"nestiq_002","property_name":"The Grove at Auburn","source":"Google Reviews","author":"John Dorlon","date":"2025-03-01","rating":1,"text":"We had mold for months and the lead maintenance guy tried to cover it up by locking us out of our own service closet.","themes":["mold","maintenance cover-up"],"sentiment":"negative","red_flags":["mold ignored and covered up","maintenance locked residents out of their closet"],"green_flags":[]},
    {"property_id":"nestiq_002","property_name":"The Grove at Auburn","source":"Google Reviews","author":"Kathleen Tibbets","date":"2024-09-01","rating":2,"text":"Son's air conditioning worked on four times. Had to put him in a hotel for a week. Maintenance backlog is long. Dryer broken for two months.","themes":["AC","maintenance backlog"],"sentiment":"negative","red_flags":["AC broken repeatedly with no urgency","maintenance backlog","dryer broken for months"],"green_flags":[]},
    {"property_id":"nestiq_002","property_name":"The Grove at Auburn","source":"Google Reviews","author":"Owen N.","date":"2025-09-25","rating":5,"text":"I love living here. 90% of experience fantastic. Management incredible, service team quick and helpful, amenities clean and fun. Only complaints: volleyball pit sand overflowing a bit, resigning process hectic.","themes":["management","amenities","maintenance"],"sentiment":"positive","red_flags":["resigning process disorganized"],"green_flags":["great management","quick maintenance","clean amenities"]},
    {"property_id":"nestiq_002","property_name":"The Grove at Auburn","source":"Google Reviews","author":"Michael Li Calzi","date":"2025-02-01","rating":5,"text":"Super affordable, close to campus, amazing gym/clubhouse/pool, friendly staff, fun activities all the time, two Tiger Transit routes that stop at the Grove. Who wouldn't want to live here?","themes":["price","location","amenities","tiger transit"],"sentiment":"positive","red_flags":[],"green_flags":["two tiger transit routes","close to campus","great amenities","affordable"]},
    {"property_id":"nestiq_002","property_name":"The Grove at Auburn","source":"Google Reviews","author":"Emmalee J.","date":"2025-02-01","rating":5,"text":"Lived here a year. Rooms are spacious especially closets, fully furnished. Maintenance fairly quick. Price is the best in town.","themes":["price","space","furnished","maintenance"],"sentiment":"positive","red_flags":[],"green_flags":["best price in Auburn","spacious rooms","fully furnished","quick maintenance"]},
    {"property_id":"nestiq_002","property_name":"The Grove at Auburn","source":"Google Reviews","author":"Aiden Sallin","date":"2024-10-01","rating":2,"text":"Lived here because it was cheapest at walking distance to campus and got treated accordingly. Car towed from feet away from my doorstep. Apartment not clean on move-in.","themes":["parking","move-in cleanliness","towing"],"sentiment":"negative","red_flags":["car towed from resident parking","apartment dirty on move-in"],"green_flags":["cheapest walking-distance option"]},
    {"property_id":"nestiq_002","property_name":"The Grove at Auburn","source":"Facebook","author":"Tara Parsons","date":"2025-11-04","rating":4,"text":"We looked at both Grove and Logan Square and thought Grove would be better. Experience this year has been mostly good. We chose the older style unit not yet renovated.","themes":["comparison","older units"],"sentiment":"positive","red_flags":["older unrenovated units available"],"green_flags":["better than Logan Square per comparison"]},
    {"property_id":"nestiq_002","property_name":"The Grove at Auburn","source":"Facebook","author":"Marie Mcintosh","date":"2025-11-04","rating":5,"text":"My daughter is in her second year there and we signed a lease for next year also. No issues. Been great for her.","themes":["overall satisfaction","renewal"],"sentiment":"positive","red_flags":[],"green_flags":["renewed for third year","no issues"]},

    # The Standard at Auburn
    {"property_id":"nestiq_011","property_name":"The Standard at Auburn","source":"Google Reviews","author":"Rainer Radtke","date":"2026-04-01","rating":1,"text":"4 years here. Constant fire alarms lasting 3-4 hours. WiFi goes out at least 24 hours every month. Constant amenities not working. Something is always broken and never gets resolved. Would not recommend for the price.","themes":["fire alarms","wifi","amenities broken","price value"],"sentiment":"negative","red_flags":["fire alarms lasting 3-4 hours","wifi out 24+ hours monthly","amenities permanently broken"],"green_flags":[]},
    {"property_id":"nestiq_011","property_name":"The Standard at Auburn","source":"Google Reviews","author":"Jim B","date":"2025-09-01","rating":1,"text":"They will fee you to death. Large application fee, small security deposit so they keep your money upfront. Staff difficulty helping residents.","themes":["fees","application costs","staff"],"sentiment":"negative","red_flags":["excessive fee structure","large non-refundable application fee","security deposit intentionally small"],"green_flags":[]},
    {"property_id":"nestiq_011","property_name":"The Standard at Auburn","source":"Google Reviews","author":"SK Coussons","date":"2024-08-01","rating":1,"text":"Two grown men entered an apartment claiming they worked for the property at 7:30pm without proper notice. Multiple people have complained. No response from management.","themes":["safety","unauthorized entry","management unresponsive"],"sentiment":"negative","red_flags":["unauthorized entry by staff without notice","management did not respond to safety complaint"],"green_flags":[]},
    {"property_id":"nestiq_011","property_name":"The Standard at Auburn","source":"Google Reviews","author":"mia ryan","date":"2024-01-01","rating":1,"text":"Brother and 3 roommates charged almost $725 EACH for new carpet at end of lease. They do not respond to emails or answer phones. Staff young and untrained.","themes":["security deposit deductions","carpet charges","staff incompetence"],"sentiment":"negative","red_flags":["$725 per person carpet charge at move-out","emails ignored","staff young and unknowledgeable"],"green_flags":[]},
    {"property_id":"nestiq_011","property_name":"The Standard at Auburn","source":"Google Reviews","author":"Josh Long","date":"2024-01-01","rating":1,"text":"100% worst apartment in Auburn. Lived here 2 years. Pool open maybe 3 total months. Hot tub never warm. TV broken for 6 months with no replacement despite it being in the lease.","themes":["amenities not working","pool","broken TV"],"sentiment":"negative","red_flags":["pool only open 3 months in 2 years","broken TV never replaced","hot tub never functional"],"green_flags":[]},
    {"property_id":"nestiq_011","property_name":"The Standard at Auburn","source":"Google Reviews","author":"Keller Allen","date":"2026-02-01","rating":3,"text":"Good spot. Slow maintenance on amenities but quick response for appliances.","themes":["amenities","maintenance split"],"sentiment":"mixed","red_flags":["amenity maintenance slow"],"green_flags":["quick appliance maintenance","good location"]},
    {"property_id":"nestiq_011","property_name":"The Standard at Auburn","source":"Google Reviews","author":"Reese Modlinger","date":"2025-01-01","rating":4,"text":"Lived here 3 years. Other residents cause a lot of problems people complain about, which is fair. Overall very livable and enjoyed my time. Great location with everything walking distance.","themes":["location","residents","amenities"],"sentiment":"positive","red_flags":["other residents cause problems"],"green_flags":["great location","walkable","nice amenities when working"]},
    {"property_id":"nestiq_011","property_name":"The Standard at Auburn","source":"Google Reviews","author":"Robert","date":"2024-01-01","rating":4,"text":"Made some of my best friends using the amenities — rooftop pool, gym, sauna, lobby games. Great community.","themes":["community","amenities","rooftop pool","sauna"],"sentiment":"positive","red_flags":[],"green_flags":["rooftop pool","sauna","great social community","gym"]},

    # Eagles West
    {"property_id":"nestiq_017","property_name":"Eagles West Apartments","source":"SatisFacts Verified","author":"Current Resident 1411978","date":"2026-03-23","rating":5,"text":"Very responsive office staff and maintenance. Communicated clearly when issues happen. When something breaks they are very quick. Definitely one of the nicest places to live in Auburn.","themes":["maintenance","communication","staff"],"sentiment":"positive","red_flags":[],"green_flags":["best maintenance response in Auburn","clear communication","quick fixes"]},
    {"property_id":"nestiq_017","property_name":"Eagles West Apartments","source":"SatisFacts Verified","author":"Current Resident 1413660","date":"2026-04-01","rating":5,"text":"Amazing staff, great job. Love Eagles West, would 100% recommend. Close walk to everything, fun events, complex always looks good.","themes":["staff","location","events","cleanliness"],"sentiment":"positive","red_flags":[],"green_flags":["walking distance to campus","frequent events","well maintained"]},
    {"property_id":"nestiq_017","property_name":"Eagles West Apartments","source":"SatisFacts Verified","author":"Current Resident 1173575","date":"2024-08-29","rating":5,"text":"My apartment is fantastic. Staff is kind. Only had two bugs in a year and a half. There is nowhere better to live in Auburn.","themes":["apartment quality","staff","overall"],"sentiment":"positive","red_flags":[],"green_flags":["best apartment in Auburn per resident","kind staff","well-maintained unit"]},
    {"property_id":"nestiq_017","property_name":"Eagles West Apartments","source":"SatisFacts Verified","author":"Current Resident 1246758","date":"2024-04-24","rating":4,"text":"Main draw is proximity to campus — can walk anywhere in 20-25 min. Main annoyance is the train noise — apartment is right across from tracks and you will definitely notice it.","themes":["location","noise","train"],"sentiment":"mixed","red_flags":["loud train noise from nearby tracks"],"green_flags":["walking distance to everywhere"]},
    {"property_id":"nestiq_017","property_name":"Eagles West Apartments","source":"Yelp","author":"Abbey J.","date":"2023-07-26","rating":3,"text":"Lived here 2 years, fairly decent. Extremely pet friendly, community clean and peaceful, maintenance REALLY helpful — came at 8:30pm off the clock. However apartments overpriced for what you get — cramped, paper thin walls, could clearly hear every conversation. Mold in bathroom, ant infestation, AC broke 5 times.","themes":["maintenance","pet-friendly","thin walls","mold","overpriced"],"sentiment":"mixed","red_flags":["paper thin walls","mold in bathroom","AC broke 5 times","ant infestation","overpriced for unit quality"],"green_flags":["exceptional maintenance response","pet-friendly","clean community","peaceful"]},
    {"property_id":"nestiq_017","property_name":"Eagles West Apartments","source":"Yelp","author":"Mazie C.","date":"2023-03-08","rating":5,"text":"Lived in a one bedroom for two years and absolutely love it. Maintenance always extremely prompt. Grounds well maintained, super clean, laid back atmosphere. 10 min walk to Lowder, Tiger Transit stops nearby. Very pet friendly.","themes":["maintenance","pet-friendly","cleanliness","location"],"sentiment":"positive","red_flags":["parking spaces very small"],"green_flags":["exceptional maintenance","pet-friendly","clean grounds","laid-back vibe"]},
    {"property_id":"nestiq_017","property_name":"Eagles West Apartments","source":"Yelp","author":"Katie B.","date":"2023-01-05","rating":5,"text":"Love living at Eagles West. They make everything easy, food trucks and events. Staff friendly. Older complex but maintenance comes as soon as possible. Great place.","themes":["staff","events","maintenance"],"sentiment":"positive","red_flags":["older building so things break"],"green_flags":["food trucks","resident events","friendly staff","quick maintenance"]},

    # 320 West Mag
    {"property_id":"nestiq_015","property_name":"320 West Mag","source":"Reddit r/auburn","author":"AnxietySlow8468","date":"2024-01-01","rating":5,"text":"320 is the best but also the hardest to sign at.","themes":["best overall","high demand"],"sentiment":"positive","red_flags":["extremely competitive to get a unit"],"green_flags":["considered best student housing in Auburn"]},
    {"property_id":"nestiq_015","property_name":"320 West Mag","source":"Reddit r/auburn","author":"Then-Opportunity-415","date":"2026-02-01","rating":5,"text":"Sublease available — directly across the street from campus, most sought-after location. Balcony, multi-level fitness center, elevated pool overlooking campus, 24-hour security, Tiger Transit, study rooms on all levels, Ross House Coffee Shop, secured parking garage, Chick-fil-A on site, high-speed WiFi, pet-friendly.","themes":["location","amenities","chick-fil-a","coffee shop","security","pool"],"sentiment":"positive","red_flags":[],"green_flags":["directly across from campus","chick-fil-a on site","24-hour security","elevated pool overlooking campus","coffee shop in building"]},
]


def calculate_summary(reviews):
    total = len(reviews)
    if not total:
        return {}
    positive = sum(1 for r in reviews if r["sentiment"] == "positive")
    negative = sum(1 for r in reviews if r["sentiment"] == "negative")
    avg_rating = round(sum(r["rating"] for r in reviews) / total, 1)
    sentiment_pct = round((positive / total) * 100)
    overall = "positive" if avg_rating >= 4.0 else "mixed" if avg_rating >= 3.0 else "negative"
    all_red = [f for r in reviews for f in r.get("red_flags", [])]
    all_green = [f for r in reviews for f in r.get("green_flags", [])]
    top_red = [f for f, _ in Counter(all_red).most_common(5)]
    top_green = [f for f, _ in Counter(all_green).most_common(5)]
    return {"overall": overall, "avg_rating": avg_rating, "sentiment_score": sentiment_pct, "count": total, "positive_count": positive, "negative_count": negative, "top_red_flags": top_red, "top_green_flags": top_green}


def seed_reviews():
    print("\n" + "="*60)
    print("  NESTIQ — Social Proof Review Seeder")
    print("="*60)
    _db.property_reviews.drop()
    _db.property_review_summaries.drop()
    print("Dropped existing review collections.")
    now = datetime.utcnow().isoformat()
    for r in REVIEWS:
        r["seeded_at"] = now
        r["verified"] = True
    _db.property_reviews.insert_many(REVIEWS)
    print(f"\n✅ Inserted {len(REVIEWS)} reviews.")
    property_ids = list(set(r["property_id"] for r in REVIEWS))
    for pid in property_ids:
        prop_reviews = [r for r in REVIEWS if r["property_id"] == pid]
        summary = calculate_summary(prop_reviews)
        summary["property_id"] = pid
        summary["property_name"] = prop_reviews[0]["property_name"]
        summary["updated_at"] = now
        _db.property_review_summaries.insert_one(summary)
    _db.property_reviews.create_index("property_id")
    _db.property_reviews.create_index("sentiment")
    print(f"✅ Created {len(property_ids)} summaries and indexes.")
    print("\nReview breakdown:")
    for pid in property_ids:
        prop_reviews = [r for r in REVIEWS if r["property_id"] == pid]
        s = calculate_summary(prop_reviews)
        print(f"  {prop_reviews[0]['property_name']}: {s['count']} reviews — {s['overall'].upper()} ({s['avg_rating']}★, {s['sentiment_score']}% positive)")
    print("\n" + "="*60)
    print("  ✅ Social proof database ready.")
    print("="*60)


if __name__ == "__main__":
    seed_reviews()
